@host = http://localhost:3000
@urlClientes = /api/clientes

@urlHoteles = /api/hoteles

@urlViajes = /api/viajes


##### API de Clientes #####
# GET http://localhost:3000/api/clientes
GET {{host}}{{urlClientes}}

###
GET {{host}}{{urlClientes}}/9

###
POST {{host}}{{urlClientes}}
Content-Type: application/json

{
    "nombre": "Peter",
    "apellidos": "Collins",
    "direccion": "Av. Palo 23",
    "telefono": "746555123",
    "fecha_nacimiento": "1979-02-17 23:01:00.00",
    "email": "pc@gmail.com",
    "dni": "33345678A"
  }

###
DELETE {{host}}{{urlClientes}}/11


##### API de Hoteles #####
GET {{host}}{{urlHoteles}}




##### API de Viajes #####
GET {{host}}{{urlViajes}}


