@host = http://localhost:3000
@urlClientes = /api/clientes

@urlHoteles = /api/hoteles

@urlViajes = /api/viajes


##### API de Clientes #####
# GET http://localhost:3000/api/clientes
GET {{host}}{{urlClientes}}



##### API de Hoteles #####
GET {{host}}{{urlHoteles}}




##### API de Viajes #####
GET {{host}}{{urlViajes}}


